### ISSUE TITLE
Dashboard: memory/pointer error

### ISSUE THREAD

**Issue by arunoruto** [almeidapaulopt/tsdproxy#57]
I wanted to try out the dashboard, but upon running the curl command, for testing, I got the following error:
```log
tsdproxy  | 2024/11/28 14:44:33 http: panic serving 127.0.0.1:42276: runtime error: invalid memory address or nil pointer dereference
tsdproxy  | goroutine 361 [running]:
tsdproxy  | net/http.(*conn).serve.func1()
tsdproxy  | 2:44PM ERR error host=dash.king-little.ts.net method=GET module=proxymanager proxyname=dash status=502 url=/
tsdproxy  | 	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:1947 +0xbe
tsdproxy  | panic({0x105ce00?, 0x1c05aa0?})
tsdproxy  | 	/opt/hostedtoolcache/go/1.23.3/x64/src/runtime/panic.go:785 +0x132
tsdproxy  | net/url.(*URL).String(0xc0028a25a0?)
tsdproxy  | 	/opt/hostedtoolcache/go/1.23.3/x64/src/net/url/url.go:832 +0x2c
tsdproxy  | github.com/almeidapaulopt/tsdproxy/internal/dashboard.(*Dashboard).AddRoutes.(*Dashboard).index.func1({0x1433368, 0xc0028a25a0}, 0x46c5bd?)
tsdproxy  | 	/home/runner/work/tsdproxy/tsdproxy/internal/dashboard/dash.go:40 +0xdd
tsdproxy  | net/http.HandlerFunc.ServeHTTP(0xc00011c2a0?, {0x1433368?, 0xc0028a25a0?}, 0xc000296ad0?)
tsdproxy  | 	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:2220 +0x29
tsdproxy  | net/http.(*ServeMux).ServeHTTP(0x40?, {0x1433368, 0xc0028a25a0}, 0xc002832280)
tsdproxy  | 	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:2747 +0x1ca
tsdproxy  | github.com/almeidapaulopt/tsdproxy/internal/core.(*HTTPServer).StartServer.LoggerMiddleware.func1({0x1433278, 0xc0028280e0}, 0xc002832280)
tsdproxy  | 	/home/runner/work/tsdproxy/tsdproxy/internal/core/log.go:83 +0x9f
tsdproxy  | net/http.HandlerFunc.ServeHTTP(0x46b499?, {0x1433278?, 0xc0028280e0?}, 0xc000296b70?)
tsdproxy  | 	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:2220 +0x29
tsdproxy  | net/http.serverHandler.ServeHTTP({0xc0028a24b0?}, {0x1433278?, 0xc0028280e0?}, 0x6?)
tsdproxy  | 	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:3210 +0x8e
tsdproxy  | 	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:2092 +0x5d0
tsdproxy  | created by net/http.(*Server).Serve in goroutine 18
tsdproxy  | 	/opt/hostedtoolcache/go/1.23.3/x64/src/net/http/server.go:3360 +0x485
tsdproxy  | 2024/11/28 14:44:33 http: proxy error: EOF
```

**Comment by almeidapaulopt** [comment]
yes it's a known situation. It still need some work to do, sorry. 
I will give mo feedback soon in #14
